name: langsplat_v2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - plyfile
  - tqdm
  - opencv
  - tensorboard
  - jaxtyping
  - matplotlib
  - typing
  - pathlib
  - scikit-learn
  - open-clip-torch
  - numpy=1.26.4
